name: what-is-dask
channels:
  - conda-forge
  - defaults
dependencies:
  - dask=2022.7.0
  - dask-ml=2022.5.27
  - ipykernel=6.15.2
  - matplotlib=3.5.2
  - numpy=1.21.5
  - pandas=1.4.4
  - python=3.9.13
  - python-graphviz=0.20.1
  - scikit-learn=1.1.2
